Algoritmo "LOOPING - PARA"
// Disciplina   : Cadastro de Livros
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Fazer um cadastro maior usando um Looping para
// Autor(a)    : Maxswell Sousa Diniz
// Data atual  : 28/06/2021

Var
livro,autor,editora:caracter
ano:inteiro
// looping responsavel pela repetição usando para e temos que ter um contador ou cont.
contador:inteiro

Inicio
Escreval ("")
Escreval ("_______________________________________________________________________")
Escreval ("          CADASTRO DE LIVROS - MAXIMUS EDIÇÃO                          ")
Escreval ("_______________________________________________________________________")
ESCREVAL ("")
para contador<-0 ate 3 faca      // para repetir a quantidade do comando colocamos isso seguido da quantidaded e se por 1 e 3 ele rodará 3 não 4 pq conta o 0e repetição
Escreval ("_______________________________________________________________________")
ESCREVAL ("")
Escreva (" Nome do livro:")
leia (livro)
Escreval ("_______________________________________________________________________")
ESCREVAL ("")
Escreva ("Nome do Autor:")
leia (autor)
Escreval ("_______________________________________________________________________")
ESCREVAL ("")
Escreval ("_______________________________________________________________________")
ESCREVAL ("")
Escreva (" Nome da Editora:")
leia (editora)
Escreval ("_______________________________________________________________________")
ESCREVAL ("")
Escreva (" Qual é o ano do Livro:")
leia (ano)

fimpara


Fimalgoritmo

